# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherStatistics' do
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxAlamofire'
  pod 'Material', '~> 2.0'
  pod 'Charts'
end

target 'WeatherStatistics-IOS' do
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxAlamofire'
end