# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherStatistics' do
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxAlamofire'
  pod 'Material', '~> 2.0'
  pod 'Charts', '~> 3.0.1'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end

target 'WeatherStatistics-IOS' do
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxAlamofire'
end